### PR TITLE
arm64: configs: generate on7xltechn defconfig 

### PR DESCRIPTION
**Pull request by Cyborg2017**

### CODE REVIEW

**Comment by minz1** [comment]
You should rebase onto the latest cm-14.1 branch, and regen your defconfig when you do so. Also, can you test the kernel with the defconfig first, before the PR?

**Comment by Cyborg2017** [comment]
For "cm-14.1-staging" ?

**Comment by minz1** [comment]
Yeah, doing it on staging would be best

**Comment by Cyborg2017** [comment]
okay,I will try it again,and test it first

**Pull request closed without merging**
